FROM ruby:2.5-stretch

LABEL maintainer="Carsten Nielsen <heycarsten@gmail.com>"

ENV POSTGRES_VERSION=9.6
ENV NODE_DIST=10.x
ENV PGUSER=postgres
ENV PATH=/lcboapi/bin:$PATH
ENV HOME=/lcboapi

# Install basics
RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y -qq install \
    software-properties-common \
    apt-transport-https \
    build-essential \
    git-core \
    openssl \
    libssl-dev \
    acl \
    zip \
    postgresql-client-$POSTGRES_VERSION \
    libpq-dev

# Install Node and Yarn for Rails AssetPipeline (5.2+)
RUN curl -sL https://deb.nodesource.com/setup_$NODE_DIST | bash - && \
    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get -y -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y -qq install nodejs yarn

RUN mkdir -p $HOME

WORKDIR $HOME

COPY Gemfile /lcboapi
COPY Gemfile.lock /lcboapi

RUN bundle install
