source 'https://rubygems.org'

gem 'kramdown'
gem 'middleman',       '~> 3.3.7'
gem 'middleman-bower'
gem 'middleman-blog'
gem 'react-source',    '0.12.0'
gem 'middleman-react', github: 'aldogroup/middleman-react', ref: '3689c947'
gem 'bourbon'
